export const COLLECTION_SUBMIT_START = "COLLECTION/SUBMIT_START";
export const COLLECTION_SUBMIT_SUCCESS = "COLLECTION/SUBMIT_SUCCESS";
export const COLLECTION_SUBMIT_FAILURE = "COLLECTION/SUBMIT_FAILURE";

export const COLLECTION_FETCH_START = "COLLECTION/FETCH_START";
export const COLLECTION_FETCH_SUCCESS = "COLLECTION/FETCH_SUCCESS";
export const COLLECTION_FETCH_FAILURE = "COLLECTION/FETCH_FAILURE";
