export const COLLECTION_SUBMIT_SUCCESS = "COLLECTION/SUBMIT_SUCCESS";
export const UPDATE_COLLECTION_SUCCESS = "COLLECTION/UPDATE_SUCCESS";

export const COLLECTION_FETCH_START = "COLLECTION/FETCH_START";
export const COLLECTION_FETCH_SUCCESS = "COLLECTION/FETCH_SUCCESS";
export const COLLECTION_FETCH_FAILURE = "COLLECTION/FETCH_FAILURE";

export const DELETE_ITEM_SUCCESS = "ITEM/DELETE_ITEM_SUCCESS";
