export const USER_REGISTER_STARTED = "AUTH/REGISTER_STARTED";
export const USER_REGISTER_SUCCESS = "AUTH/REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "AUTH/REGISTER_FAILURE";

export const USER_LOGIN_STARTED = "AUTH/LOGIN_STARTED";
export const USER_LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "AUTH/LOGIN_FAILURE";
