export const USER_AUTH_STARTED = "AUTH/AUTH_STARTED";
export const USER_AUTH_FAILURE = "AUTH/AUTH_FAILURE";
export const USER_LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const USER_REGISTER_SUCCESS = "AUTH/REGISTER_SUCCESS";

export const USER_LOGOUT = "AUTH/USER_LOGOUT";
