export const ITEM_SUBMIT_START = "ITEM/DATA_SEND_START";
export const ITEM_SUBMIT_SUCCESS = "ITEM/DATA_SEND_SUCCESS";
export const ITEM_SUBMIT_FAILURE = "ITEM/DATA_SEND_FAILURE";

export const ITEM_FETCH_START = "ITEM/DATA_FETCH_START";
export const ITEM_FETCH_SUCCESS = "ITEM/DATA_FETCH_SUCCESS";
export const ITEM_FETCH_FAILURE = "ITEM/DATA_FETCH_FAILURE";

export const FETCH_LAST_ITEM_SUCCESS = "ITEM/FETCH_LAST_ITEM_SUCCESS";
