export const PROFILE_DATA_FETCH_START = "PROFILE/FETCH_DATA_START";
export const PROFILE_DATA_FETCH_SUCCESS = "PROFILE/FETCH_DATA_SUCCESS";
export const PROFILE_DATA_FETCH_FAILURE = "PROFILE/FETCH_DATA_FAILURE";

export const PROFILE_COLLECTION_FETCH_START = "PROFILE/FETCH_COLLECTION_START";
export const PROFILE_COLLECTION_FETCH_SUCCESS = "PROFILE/FETCH_COLLECTION_SUCCESS";
export const PROFILE_COLLECTION_FETCH_FAILURE = "PROFILE/FETCH_COLLECTION_FAILURE";

export const COLLECTION_DELETE_SUCCESS = "COLLECTION/DELETE_COLLECTION";
