export const FETCH_TAGS_START = "TAGS/FETCH_START";
export const FETCH_TAGS_SUCCESS = "TAGS/FETCH_SUCCESS";
export const FETCH_TAGS_FAILURE = "TAGS/FETCH_FAILURE";

export const CREATE_TAGS_SUCCESS = "TAGS/CREATE_SUCCESS";

export const SEARCH_TAG_SUCCESS = "TAGS/SEARCH_TAG";
