export const FETCH_TAGS_START = "TAGS/FETCH_START";
export const FETCH_TAGS_SUCCESS = "TAGS/FETCH_SUCCESS";
export const FETCH_TAGS_FAILURE = "TAGS/FETCH_FAILURE";

export const CREATE_TAGS_START = "TAGS/CREATE_START";
export const CREATE_TAGS_SUCCESS = "TAGS/CREATE_SUCCESS";
export const CREATE_TAGS_FAILURE = "TAGS/CREATE_FAILURE";
